### ISSUE TITLE
codecommit-backup: how come repositoryNames is optional?

### ISSUE THREAD

**Issue by eladb** [cloudcomponents/cdk-components#21]
I am curious what it means to define this without any repositoryNames?

https://github.com/cloudcomponents/cdk-components/blob/e3cc99226ea5ff84904813415c221de8c93456f9/packages/cdk-codecommit-backup/src/s3-codecommit-backup.ts#L22

**Comment by hupe1980** [comment]
The component then determines repositories using the aws cli:
https://github.com/cloudcomponents/cdk-components/blob/e3cc99226ea5ff84904813415c221de8c93456f9/packages/cdk-codecommit-backup/scripts/backup_codecommit.sh#L8-L14

**Comment by eladb** [comment]
Oh wow so the default is all the repositories in the account. Maybe worth mentioning in “@default”

**Comment by hupe1980** [comment]
Yes you are right. I will point this out in the documentation.

**Comment by hupe1980** [comment]
https://github.com/cloudcomponents/cdk-components/blob/a66d61eac0b4b499e7a228c2969f5e48b5c065fc/packages/cdk-codecommit-backup/src/s3-codecommit-backup.ts#L30-L35

**Comment by eladb** [comment]
You probably want to indicate that in the readme as well

On Feb 16, 2020, at 9:59 PM, Frank Hübner <notifications@github.com> wrote:

﻿

https://github.com/cloudcomponents/cdk-components/blob/a66d61eac0b4b499e7a228c2969f5e48b5c065fc/packages/cdk-codecommit-backup/src/s3-codecommit-backup.ts#L30-L35

**Comment by hupe1980** [comment]
It is now also in the readme
