### ISSUE TITLE
Slack Notifier:  expose Api 

### ISSUE THREAD

**Issue by brettswift** [cloudcomponents/cdk-components#24]
I'd gladly submit a PR if you're ok with this.   I'm interested in accessing the Api Gateway a little easier than using the escape hatch to get to the L1 constructs.   Would you be ok with that? 

The reason being is I'd like to add a route53 entry, and change the name so I can tell the difference between them in the console, and maybe a few other properties. 

And thanks for publishing this! :beer:

**Comment by hupe1980** [comment]
Yes that's okay. You're welcome to create a PR
