### ISSUE TITLE
[PullRequestCheck] Error using package, no found resource lambda

### ISSUE THREAD

**Issue by pcariel** [cloudcomponents/cdk-components#4]
Hi, @hupe1980.

I like your work,
I have a problem when I try to use the package.

```ts
import { PullRequestCheck } from "@cloudcomponents/cdk-pull-request-check";
new PullRequestCheck(this, "PullRequestCheck", {
      repository,
      buildSpec: BuildSpec.fromObject({
        version: "0.2",
        phases: {
          build: {
            commands: ['echo "Hello, CodeBuild!"']
          }
        }
      })
    });
```

  at new PullRequestCheck (/node_modules/@cloudcomponents/cdk-pull-request-check/src/pull_request_check.ts:48:37)
ENOENT: no such file or directory, stat PATH_MY_APP/resources'

can you help me with this?
Thank you

**Comment by hupe1980** [comment]
@pcariel I have fixed the issue
