### ISSUE TITLE
[PullRequestCheck] Organize lambda by folders

### ISSUE THREAD

**Issue by pcariel** [cloudcomponents/cdk-components#5]
Hello, @hupe1980 . Maybe this requirement is not relevant, you can close if you wish.

Is there a possibility to forget the lambda in folders? to be able to view only the source file of it?

Sorry for my bad English.
Thank you
![image](https://user-images.githubusercontent.com/12478330/62255780-1dbf6800-b3d5-11e9-9981-daabdb1043f5.png)

**Comment by hupe1980** [comment]
I do not know if I understood you correctly. 😀If you do not want to upload the lambdas, you could also pass the source code inline in this specific case

For example:
```javascript
const fn = new Function(this, 'MyFunction', {
    runtime: lambda.Runtime.NODEJS_10_X,
    handler: 'index.handler',
    code: lambda.Code.inline('exports.handler = async (event) { return { text: 'Hello World!' }),
});
```

Does this answer your question?

**Comment by pcariel** [comment]
Hi, @hupe1980.
Sorry if you explain me wrong, the requirement is; organize the lambda functions by folder to be able to display only the function code per AWS UI.

cdk-pull-request-check/resources/code_build_result/handler.py
cdk-pull-request-check/resources/pull_request/handler.py

in this way you can only visualize the code of that lambda and not all in the same lambda

**Comment by hupe1980** [comment]
@pcariel Ok I understand. You're right! We can do that:
```bash
cdk-pull-request-check/lambdas/code-build-result/handler.py
cdk-pull-request-check/lambdas/pull-request/handler.py
```
Would you like to create a pull request for it?
