### ISSUE TITLE
[PullRequestCheck] Feature Slack notification

### ISSUE THREAD

**Issue by pcariel** [cloudcomponents/cdk-components#7]
@hupe1980, Is it possible to add the slack notification?

**Comment by hupe1980** [comment]
Yes, we can extend the cdk-pullrequest-check to optional publish in a sns topic. Based on that, we could then implement a slack implementation in cdk-codepipeline-slack.

Do you want to try it?

**Comment by pcariel** [comment]
Of course, I will. Any news I inform you.
Thank you
