### ISSUE TITLE
Publish as part of the CDK?

### ISSUE THREAD

**Issue by eladb** [cloudcomponents/cdk-components#8]
Would you be interested in submitting a PR to publish this as part of the AWS CDK itself?

**Comment by hupe1980** [comment]
@eladb Yes I am interested. Is it enough to rename the packages (eg @aws-cdk/pull-request-check) and adapt them to your build / test tools? Or do I have to adapt something else?

**Comment by jewelsjacobs** [comment]
Other than needing to manually tweak the website bucket ACL and Bucket policy to I'm using this successfully in my pipeline. Adding this to CDK would be fantastic!
